import { useEffect, useMemo, useState } from 'react'
import { Activity, AlertTriangle, Beaker, CheckCircle2, ChevronRight, CircleOff, Download, Gauge, Menu, Pause, Play, RotateCcw, Search, ShieldAlert, SlidersHorizontal, ToggleLeft, ToggleRight, Wifi, X } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { classify } from './simulation/classifier'
import { advance, initialEngine, type EngineState } from './simulation/engine'
import { scenarios } from './simulation/scenarios'
import { blankSensors } from './simulation/telemetry'
import type { Classification, Sensors, SystemMode } from './types'

const labels: Record<string, string> = { ph: 'pH', tds: 'TDS', turbidity: 'Turbidity', colourIntensity: 'RGB colour', flowRate: 'Flow' }
const units: Record<string, string> = { ph: '', tds: 'mg/L', turbidity: 'NTU', colourIntensity: '/ 100', flowRate: 'L/min' }
const ranges: Record<string, string> = { ph: '6.5 – 8.5', tds: '0 – 1,500', turbidity: '0 – 20', colourIntensity: '0 – 55', flowRate: '0 – 40' }
const tone = (state: string) => state === 'COMPLIANT' ? 'good' : state === 'WARNING' ? 'warn' : 'bad'

function App() {
  const [engine, setEngine] = useState<EngineState>(() => { try { return JSON.parse(localStorage.getItem('chromaguard-engine') || 'null') || initialEngine() } catch { return initialEngine() } })
  const [sensors, setSensors] = useState<Sensors>(blankSensors), [running, setRunning] = useState(true), [mode, setMode] = useState<SystemMode>('AUTOMATIC'), [bypass, setBypass] = useState(false), [pump, setPump] = useState(false), [speed, setSpeed] = useState(1), [query, setQuery] = useState(''), [filter, setFilter] = useState('ALL'), [mobile, setMobile] = useState(false)
  const result = useMemo(() => classify(sensors), [sensors])
  useEffect(() => { localStorage.setItem('chromaguard-engine', JSON.stringify(engine)) }, [engine])
  useEffect(() => { if (!running) return; const id = window.setInterval(() => setEngine(e => advance({ ...e, pump }, sensors, mode, bypass)), 2400 / speed); return () => clearInterval(id) }, [running, sensors, mode, bypass, pump, speed])
  const applyScenario = (key: string) => { const scenario = scenarios[key]; setSensors(scenario.values); setBypass(key === 'bypass'); if (key === 'full') setEngine(e => ({ ...e, tankLevel: 98 })) }
  const reset = () => { setEngine(initialEngine()); setSensors(blankSensors); setBypass(false); setRunning(true) }
  const events = engine.events.filter(e => (filter === 'ALL' || e.classification === filter) && JSON.stringify(e).toLowerCase().includes(query.toLowerCase())).slice().reverse()
  const exportCsv = () => { const rows = ['timestamp,ph,tds,turbidity,colourIntensity,flowRate,classification,valve,pump,mode,rules', ...engine.events.map(e => [e.timestamp, e.values.ph, e.values.tds, e.values.turbidity, e.values.colourIntensity, e.values.flowRate, e.classification, e.valve, e.pump, e.mode, `"${e.rules.join('; ')}"`].join(','))]; const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([rows.join('\n')], { type: 'text/csv' })); a.download = 'chromaguard-event-log.csv'; a.click(); URL.revokeObjectURL(a.href) }
  const stateTone = tone(engine.systemState), diverted = engine.divertedVolume.toFixed(1), compliance = engine.totalVolume ? Math.max(0, Math.round(100 - engine.violations / Math.max(1, engine.samples.length) * 100)) : 100
  return <div className="min-h-screen"><header className="topbar"><div className="brand"><div className="brand-mark">CG</div><div><div className="brand-title">Chroma<span>Guard</span></div><div className="eyebrow">EFFLUENT COMPLIANCE SYSTEM</div></div></div><div className="header-meta"><span className="pill"><Wifi size={14}/> Unit CG-07 / Dyeing Line 2</span><span className="pill live"><span className="dot"/> SIMULATION {running ? 'RUNNING' : 'PAUSED'}</span><button className="icon-btn mobile-menu" onClick={() => setMobile(!mobile)} aria-label="Toggle menu">{mobile ? <X/> : <Menu/>}</button></div></header>
    <main className="shell"><section className="hero"><div><p className="eyebrow">CONTROL ROOM / LIVE DIGITAL TWIN</p><h1>Sense. Classify. Divert.</h1><p className="subtitle">A transparent prototype for stopping non-compliant textile effluent before it reaches the normal outlet.</p></div><div className="hero-actions"><button className="btn primary" onClick={() => setRunning(!running)}>{running ? <Pause size={16}/> : <Play size={16}/>} {running ? 'Pause twin' : 'Resume twin'}</button><button className="btn" onClick={reset}><RotateCcw size={16}/> Reset</button></div></section>
      <div className="grid state-grid"><section className={`card state-card ${stateTone}`}><div className="section-top"><div><p className="eyebrow">SYSTEM STATE</p><h2><span className="state-icon">{engine.systemState === 'COMPLIANT' ? <CheckCircle2/> : engine.systemState === 'SENSOR_FAULT' ? <CircleOff/> : <ShieldAlert/>}</span>{engine.systemState.replace('_', ' ')}</h2></div><span className="status-badge">{engine.valve === 'DIVERTING' ? 'DIVERSION ACTIVE' : engine.valve}</span></div><p className="state-reason">{bypass ? 'Maintenance bypass is enabled. This intentional override is logged and visible.' : result.rules.length ? result.rules.map(r => r.label).join(' · ') : 'All critical readings are within the prototype safe bands.'}</p><div className="state-footer"><span><span className="led"/> Valve: <strong>{engine.valve}</strong></span><span>Tank {engine.tankLevel.toFixed(0)}%</span><span>Streak {engine.compliantStreak}/2</span></div></section><section className="card score-card"><div className="section-top"><div><p className="eyebrow">RULE-BASED DECISION</p><h2>Compliance score</h2></div><Gauge className={result.score > 70 ? 'text-emerald-400' : 'text-red-400'}/></div><div className="score"><strong>{result.score}</strong><span>/ 100</span><div className="score-bar"><i style={{ width: `${result.score}%` }}/></div></div><p className="muted">{result.confidence} confidence · not an ML probability</p></section></div>
      <section className="card scenarios"><div className="section-top"><div><p className="eyebrow">REPRODUCIBLE INPUTS</p><h2>Scenario console</h2></div><span className="muted">Click to inject deterministic readings</span></div><div className="scenario-row">{Object.entries(scenarios).map(([key, scenario]) => <button key={key} className="scenario" onClick={() => applyScenario(key)}>{scenario.label}</button>)}</div></section>
      <section className="card process"><div className="section-top"><div><p className="eyebrow">PROCESS ROUTE</p><h2>Physical decision path</h2></div><span className={`route-label ${stateTone}`}>{engine.valve === 'DIVERTING' ? 'OUTLET BLOCKED · HOLDING TANK' : 'NORMAL OUTLET ACTIVE'}</span></div><div className="route"><Node icon={<Beaker/>} label="Dyeing unit"/><ChevronRight/><Node icon={<Activity/>} label="Sensor pod" active/><ChevronRight/><Node icon={<SlidersHorizontal/>} label="Fusion classifier" active/><ChevronRight/><Node icon={<ShieldAlert/>} label="Decision" active/><div className="branches"><div className={engine.valve === 'NORMAL' ? 'branch active good' : 'branch'}><span/> Normal discharge</div><div className={engine.valve === 'DIVERTING' ? 'branch active bad' : 'branch'}><span/> Solenoid → holding tank {pump ? '→ pump' : ''}</div></div></div></section>
      <div className="grid sensor-grid">{(Object.keys(labels) as Array<keyof Sensors>).map(key => <SensorCard key={key} name={labels[key]} value={sensors[key]} unit={units[key]} range={ranges[key]} fault={sensors[key] === null}/>)}</div>
      <div className="grid chart-grid"><ChartCard title="Sensor readings over time"><ResponsiveContainer width="100%" height={220}><LineChart data={engine.samples.map((s, i) => ({ ...s, i: i + 1 }))}><CartesianGrid stroke="#36252a" vertical={false}/><XAxis dataKey="i" stroke="#806d73"/><YAxis stroke="#806d73"/><Tooltip contentStyle={{ background: '#24171b', border: '1px solid #493238' }}/><Line type="monotone" dataKey="ph" stroke="#f0c36a" dot={false}/><Line type="monotone" dataKey="turbidity" stroke="#d96d65" dot={false}/><Line type="monotone" dataKey="tds" stroke="#b487ff" dot={false}/></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Compliance & diverted volume"><ResponsiveContainer width="100%" height={220}><AreaChart data={engine.samples.map((s, i) => ({ ...s, i: i + 1 }))}><CartesianGrid stroke="#36252a" vertical={false}/><XAxis dataKey="i" stroke="#806d73"/><YAxis stroke="#806d73"/><Tooltip contentStyle={{ background: '#24171b', border: '1px solid #493238' }}/><Area type="monotone" dataKey="score" stroke="#67d69c" fill="#67d69c" fillOpacity={.12}/><Line type="monotone" dataKey="divertedVolume" stroke="#d96d65" dot={false}/></AreaChart></ResponsiveContainer></ChartCard></div>
      <div className="grid lower-grid"><section className="card controls"><div className="section-top"><div><p className="eyebrow">OPERATOR CONTROLS</p><h2>Actuation & safety</h2></div></div><Control label="Control mode"><select value={mode} onChange={e => setMode(e.target.value as SystemMode)}><option>AUTOMATIC</option><option>MANUAL</option></select></Control><Control label="Maintenance bypass"><button className="toggle" onClick={() => setBypass(!bypass)} aria-label="Toggle maintenance bypass">{bypass ? <ToggleRight className="on"/> : <ToggleLeft/>}</button></Control><Control label="Diversion valve"><button className="btn small" onClick={() => setEngine(e => ({ ...e, valve: e.valve === 'DIVERTING' ? 'NORMAL' : 'DIVERTING', systemState: e.valve === 'DIVERTING' ? 'COMPLIANT' : 'DIVERTING' }))}>{engine.valve === 'DIVERTING' ? 'Close diversion' : 'Open diversion'}</button></Control><Control label="Treatment pump"><button className="toggle" onClick={() => setPump(!pump)} aria-label="Toggle treatment pump">{pump ? <ToggleRight className="on"/> : <ToggleLeft/>}</button></Control><Control label={`Simulation speed (${speed}×)`}><input aria-label="Simulation speed" type="range" min=".5" max="3" step=".5" value={speed} onChange={e => setSpeed(Number(e.target.value))}/></Control></section><section className="card metrics"><div className="section-top"><div><p className="eyebrow">IMPACT METRICS</p><h2>Protection ledger</h2></div></div><div className="metric-grid"><Metric value={`${engine.totalVolume.toFixed(1)} L`} label="Water monitored"/><Metric value={`${diverted} L`} label="Wastewater diverted" bad/><Metric value={engine.violations} label="Violation events" bad/><Metric value={`${compliance}%`} label="Compliant decisions"/><Metric value={`${engine.tankLevel.toFixed(0)}%`} label="Holding tank level" warn/><Metric value="< 1 s" label="Decision time"/></div></section></div>
      <section className="card log"><div className="section-top"><div><p className="eyebrow">AUDIT TRAIL</p><h2>Event log</h2></div><div className="log-actions"><label className="search"><Search size={15}/><input value={query} onChange={e => setQuery(e.target.value)} aria-label="Search events"/></label><select value={filter} onChange={e => setFilter(e.target.value)} aria-label="Filter events"><option>ALL</option><option>NON_COMPLIANT</option><option>SENSOR_FAULT</option><option>WARNING</option><option>COMPLIANT</option></select><button className="btn small" onClick={exportCsv}><Download size={15}/> CSV</button><button className="btn small danger" onClick={() => { if (window.confirm('Clear the complete local event log?')) setEngine(e => ({ ...e, events: [] })) }}>Clear</button></div></div><div className="table-wrap"><table><thead><tr><th>Time</th><th>Classification</th><th>Rules</th><th>Valve</th><th>Pump</th><th>Mode</th></tr></thead><tbody>{events.length ? events.map(e => <tr key={e.id}><td>{new Date(e.timestamp).toLocaleTimeString()}</td><td><span className={`table-state ${tone(e.classification)}`}>{e.classification}</span></td><td>{e.rules.join(' · ') || 'All readings within bands'}</td><td>{e.valve}</td><td>{e.pump ? 'ON' : 'OFF'}</td><td>{e.mode}</td></tr>) : <tr><td colSpan={6} className="empty">No events yet. Start the twin or choose a scenario.</td></tr>}</tbody></table></div></section>
      <footer><span>ChromaGuard · HackFusion 2026 prototype</span><span>Rule model v1.0 · Local-only simulation · No regulatory certification implied</span></footer>
    </main></div>
}
function Node({ icon, label, active }: { icon: React.ReactNode; label: string; active?: boolean }) { return <div className={`node ${active ? 'active' : ''}`}><div>{icon}</div><span>{label}</span></div> }
function SensorCard({ name, value, unit, range, fault }: { name: string; value: number | null; unit: string; range: string; fault: boolean }) { return <section className={`card sensor ${fault ? 'bad' : ''}`}><div className="sensor-head"><span>{name}</span><span className={`health ${fault ? 'bad' : 'good'}`}>{fault ? 'FAULT' : 'HEALTHY'}</span></div><div className="sensor-value">{value ?? '—'} <small>{unit}</small></div><div className="sensor-foot"><span>Safe {range}</span><span className="trend">↗ live</span></div></section> }
function ChartCard({ title, children }: { title: string; children: React.ReactNode }) { return <section className="card chart"><div className="section-top"><h2>{title}</h2><span className="muted">last 60 samples</span></div>{children}</section> }
function Control({ label, children }: { label: string; children: React.ReactNode }) { return <div className="control"><span>{label}</span>{children}</div> }
function Metric({ value, label, bad, warn }: { value: string | number; label: string; bad?: boolean; warn?: boolean }) { return <div className="metric"><strong className={bad ? 'bad-text' : warn ? 'warn-text' : ''}>{value}</strong><span>{label}</span></div> }
export default App
